name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      # fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.10] # to minimise complexity we only test a single version
        # below the list of tox envs that you wish to include in the matrix
        include:
          # on all platforms and versions do everything
          - tox-envs: [docs, lint, build, test]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run for testing
        run: tox -e ${{ join(matrix.tox-envs, ',') }}
      # from https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          #fail_ci_if_error: true
          verbose: true
